# Generated by Django 3.2.4 on 2021-07-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210706_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
