# Generated by Django 3.2.4 on 2021-07-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, upload_to='auctions/static/auctions'),
        ),
    ]
