# Generated by Django 3.2.4 on 2021-07-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_listing_current_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_winner',
        ),
    ]
