# Generated by Django 3.2.4 on 2021-07-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_winner'),
        ('auctions', '0019_remove_listing_current_winner'),
    ]

    operations = [
    ]
