# Generated by Django 3.2.4 on 2021-07-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_merge_0015_winner_0019_remove_listing_current_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
