# Generated by Django 3.2.4 on 2021-07-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_listing_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
